_target_: src.models.k_mean_net.KmeanNetLightning

kmean:
  _target_: src.models.components.k_means.KmeanModel
  num_centroids: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

